### ISSUE TITLE
finish NSArray implementation

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#2074]
- [x] Complete NSArray KVO implementation #2068 
- [x] Complete NSArray URL read/write #2069 
- [x] Complete NSArray indexOf: methods #2070 
- [x] Complete NSArray enumerate #2072 
- [x] Complete NSArray descriptionWithLocale* #2073
