### ISSUE TITLE
Implement NSUndoManager

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#699]
[NSUndoManager](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSUndoManager_Class/index.html#//apple_ref/occ/instp/NSUndoManager/) is used by applications (directly/indirectly) for performing undo/redo operations.

**Comment by MSFTFox** [comment]
Sub tasks for the work to enable NSUndoManager.

- [ ] Testing for NSUndoManager and investigation on OSX #807 
- [ ] Basic Registering of Undo Events #808 
- [ ] Grouping Undo Events into undo sets #811 
- [ ] Undo Manager APIs using action names #812 
- [ ] Modifying undo/redo stack #813
- [ ] Utilize notifications for Undo operations. #814
