### ISSUE TITLE
Improve initialization performance of WinOBJC binaries

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#717]
Continue the work from 1607 on this front.  Focus is on initialization performance.
- [x] Unneeded frameworks don't have to be loaded, perhaps our dependencies are wrong. #714 
- [x] ~1/3 time is spent just loading the binaries, which is unusual. #715 
- [x] Investigate runtime changes to delay class/selector registration #716

**Comment by rajsesh-msft** [comment]
The performance investigations for 1608 are complete.  We have two follow-ups items, which we will complete in 1609.

- #912 Split up projections binaries and fix packaging to include only necessary projection modules.
- #913 Add runtime support for pre-hashed selectors to improve startup performance
