### ISSUE TITLE
Foundation priority asks from app partners and to enable some middleware

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#720]
- [x] support forward Invocation #711 
- [ ] Implement NSDecimalNumber #712 
- [x] NSUndoManager #699 
- [ ] Implement objc memory management for core foundation #719 
- [ ] Binary property lists created in reference platform would misbehave #649
