### ISSUE TITLE
Coretext : proper bridging, dwrite usage, bug fixes improvements for app partners

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#733]
- [x] Coretext sample to manually test interop #728
- [x] Coretext alignment feature is not working #644 
- [ ] CTFont and CTFontCollection support through DWrite and bridging with the UIKit types #729 
- [ ] CTFontDescriptor and UIFontDescriptor bridging #730 
- [ ] CGContext bitmap <-> CoreText with DWrite #793
- [ ] Use DWrite custom renderer to implement text "measure" using DWrite #731 
- [ ] CTDraw* apis should use DWrite to draw text #732
